#+TITLE: FZAM README

* FZAM | Fuzzy AppImage Manager
*WARNING: I am not responsible for any AppImage that is integrated to the system using fzam and it is malware.*

FZAM is a bash script that lets the user integrate their AppImages to their desktop environment easily. It uses [[https://github.com/junegunn/fzf][fzf]] as its interface.

When the user selects an AppImage, fzam extracts the .desktop file from the root of the AppImage, together with its icon (.DirIcon) and make the required changes to the .desktop
file to launch the AppImage and use its icon. 

By default the AppImage is moved into *~/Applications*, the icon in *~/Applications/.icons* and the desktop entry to *~/.local/share/applications*, although the user can easily
change them from the script itself.

Note that the user might need to edit the desktop entry of the AppImage in case of any errors.

* Depedencies
fzf
xargs
file (Some distributions include it by default but not every single one, for example Arch)
tree (Same reason as above)

* Installation
Simply download the script from the repository, make the script executable (chmod +x fzam) and place it somewhere on your system. (For example ~/.local/bin)

* Features
- Integrate AppImages
- Deleting AppImages
- List all installed AppImages

* Features that may or may not be added
- Updating. Not every single AppImage support it ([[https://github.com/AppImageCommunity/AppImageUpdate][AppImageUpdate]] is a solution to this.) 
